from __future__ import annotations

"""
Brochure render service

Renders brochure HTML from draft data and converts it to PDF bytes using
WeasyPrint if available, or returns a simple mock PDF as a fallback.
"""

from typing import Dict, Any


def _build_html(draft: Dict[str, Any]) -> str:
    hero = draft.get("hero", {})
    about = draft.get("about", {})
    why = draft.get("whyInvest", {})
    amenities = draft.get("amenities", {})
    branding = draft.get("branding", {})

    title = hero.get("title") or about.get("heading") or "Property Brochure"
    subtitle = hero.get("subtitle") or "Presented by Aura"
    body = about.get("body") or ""
    bullets = why.get("bullets") or []
    features = amenities.get("features") or []

    primary = branding.get("primary") or "#2563eb"
    secondary = branding.get("secondary") or "#9333EA"

    highlights_html = "".join(f"<li><span class='dot'></span><span>{b}</span></li>" for b in bullets)
    features_html = "".join(f"<li><span class='dot'></span><span>{f}</span></li>" for f in features)

    html = f"""
<!doctype html>
<html lang=\"en\">
  <head>
    <meta charset=\"utf-8\" />
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />
    <title>{title}</title>
    <style>
      :root {{ --primary: {primary}; --secondary: {secondary}; --bg: #f8fafc; --ink: #0f172a; --muted: #64748b; }}
      body {{ margin:0; font-family: system-ui, -apple-system, Segoe UI, Roboto, sans-serif; background: var(--bg); color: var(--ink); }}
      .wrap {{ max-width: 920px; margin: 24px auto; padding: 24px; background:#fff; border-radius: 12px; box-shadow: 0 6px 18px rgba(15,23,42,.06); border:1px solid #e5e7eb; }}
      .title {{ font-size: 28px; font-weight: 700; margin: 0; }}
      .subtitle {{ margin-top: 4px; color: var(--muted); font-size: 14px; }}
      .section {{ margin-top: 20px; }}
      .section h3 {{ font-size: 12px; text-transform: uppercase; letter-spacing:.08em; color: var(--muted); margin:0 0 8px; }}
      ul {{ list-style:none; padding:0; margin:0; }}
      li {{ display:flex; gap:8px; margin:6px 0; font-size:14px; color:#1f2937; }}
      .dot {{ width:6px; height:6px; border-radius:999px; background: var(--primary); margin-top:8px; display:inline-block; flex: 0 0 auto; }}
      .footer {{ margin-top: 22px; padding-top: 14px; border-top:1px solid #e5e7eb; color: var(--muted); font-size:12px; display:flex; justify-content:space-between; }}
    </style>
  </head>
  <body>
    <div class=\"wrap\">
      <header>
        <p class=\"subtitle\">{subtitle}</p>
        <h1 class=\"title\">{title}</h1>
      </header>

      <section class=\"section\">
        <h3>About</h3>
        <p>{body}</p>
      </section>

      <section class=\"section\">
        <h3>Highlights</h3>
        <ul>
          {highlights_html}
        </ul>
      </section>

      <section class=\"section\">
        <h3>Amenities</h3>
        <ul>
          {features_html}
        </ul>
      </section>

      <div class=\"footer\">
        <span>Generated by Aura</span>
        <span>{draft.get('templateKey','')}</span>
      </div>
    </div>
  </body>
</html>
"""
    return html


async def render_brochure_to_pdf(draft: Dict[str, Any]) -> bytes:
    """Render draft to PDF bytes. Uses WeasyPrint if available; otherwise a mock.

    This function is designed to be robust in minimal dev environments:
    - Try WeasyPrint first (best quality)
    - Fallback to ReportLab if available
    - If neither are installed, return a minimal, standards-compliant PDF
      so the brochure flow can complete in development without extra deps.
    """
    html = _build_html(draft)
    try:
        from weasyprint import HTML

        return HTML(string=html).write_pdf()
    except Exception:
        # Attempt ReportLab fallback
        try:
            from reportlab.lib.pagesizes import letter
            from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
            from reportlab.lib.styles import getSampleStyleSheet
            from io import BytesIO

            buf = BytesIO()
            doc = SimpleDocTemplate(buf, pagesize=letter)
            styles = getSampleStyleSheet()
            story = [
                Paragraph("Property Brochure (Mock)", styles["Title"]),
                Spacer(1, 12),
                Paragraph("WeasyPrint not available.", styles["Normal"]),
            ]
            doc.build(story)
            return buf.getvalue()
        except Exception:
            # Final ultra-minimal PDF fallback (valid enough for download/testing)
            # This is a tiny one-page PDF with the words "Property Brochure".
            minimal_pdf = (
                b"%PDF-1.4\n"
                b"1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj\n"
                b"2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj\n"
                b"3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792]"
                b" /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >> endobj\n"
                b"4 0 obj << /Length 55 >> stream\nBT /F1 24 Tf 72 720 Td (Property Brochure) Tj ET\nendstream endobj\n"
                b"5 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj\n"
                b"xref\n0 6\n0000000000 65535 f \n0000000010 00000 n \n0000000062 00000 n \n0000000118 00000 n \n0000000283 00000 n \n0000000418 00000 n \n"
                b"trailer << /Root 1 0 R /Size 6 >>\nstartxref\n530\n%%EOF\n"
            )
            return minimal_pdf

